config/routes.rb
DbcOverflow::Application.routes.draw do
  resources :posts do
    resources :advices
    resources :comments do
      resources :advices
    end
  end

  resources :votes, only: [:create, :update]

  root :to => "posts#index"

  devise_for :users

  get 'users/:id' => 'users#show', as: :user
  get '/about', :to => redirect('/about.html')
end

app/models/advice.rb
class Advice < ActiveRecord::Base
  belongs_to :user
  belongs_to :adviceable, polymorphic: true
  attr_accessible :content, :user_id, :adviseable_id, :adviseable_type
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  attr_accessible :text, :user_id, :post_id, :score

  belongs_to :user
  belongs_to :post
  has_many :votes, as: :voteable
  has_many :advices, as: :adviceable
  
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :text, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title, :user_id, :score

  belongs_to :user
  has_many :comments
  has_many :votes, as: :voteable
  has_many :advices, as: :adviceable

  
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  has_many :votes
  has_many :advices


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def find_vote(voteable)
    self.votes.find_by_voteable_id_and_voteable_type(voteable.id, voteable.class.name)
  end

  def vote_value(voteable)
    vote = find_vote(voteable)
    vote ? vote.value : 0
  end

  def vote_id(voteable)
    vote = find_vote(voteable)
    vote ? vote.id : 0
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, polymorphic: true
  belongs_to :user

  attr_accessible :value, :user_id, :voteable_id, :voteable_type
  validates_presence_of :user, :user_id, :voteable, :voteable_id, :voteable_type
  validates_uniqueness_of :user_id, :scope => [:voteable_id, :voteable_type], :message => "You've already voted on this."
end

app/models/votes.rb
class Votes < ActiveRecord::Base
	belongs_to :voteable, polymorphic: true
	belongs_to :user

	validates_inclusion_of :value, in [-1, 1]

end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController

  def new
      @advice = Advice.new()
      @comment = Comment.find(params[:comment_id]) if params.include?('comment_id')
      @post= Post.find(params[:post_id]) if params.include?('post_id')
  end

  def create
    Advice.create(content: params[:advice][:content],
            adviseable_id: params[:advice][:id],
          adviseable_type: params[:advice][:type],
                  user_id: current_user.id)
    redirect_to post_path(params[:post_id]), alert: "Thanks for the Advice!"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def get_voteable_object(params)
    type = params[:voteable_type]
    id = params[:voteable_id]
    type == "Comment" ? Comment.find(id) : Post.find(id)
  end

  def increment_score(voteable_object, amount)
    voteable_object.score += amount.to_i
    voteable_object.save
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
      @comment = Comment.new()
      @post= Post.find(params[:post_id])
  end

  def create
    comment = Comment.create(text: params[:comment][:text], post_id: params[:post_id], user_id: current_user.id)
    redirect_to post_path(params[:post_id]), alert: "Thanks for your comment!"
  end

  def destroy
    Comment.delete(params[:id])
    @notice = "You've deleted you're comment."
    redirect_to :back
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  include PostsHelper
  def index
    @posts = Post.order("score DESC")
  end

  def show
    @post = Post.find(params[:id])
    @post_advice = post_advise(params[:id])
    @comments = @post.comments.order("score DESC")
    @comment_advice = comment_advise(@comments) if @comments
  end

  def new
    @post = Post.new
  end

  def create
    post_params = params[:post]
    post_params[:user_id] = current_user.id
    if @post = Post.create(post_params)
      redirect_to @post
    else
      render :new
    end
  end

  def destroy
    Post.delete(params[:id])
    @notice = "You've deleted you're post."
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
    @gravatar = Digest::MD5.hexdigest(@user.email.downcase)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    voteable_object = get_voteable_object(params[:vote])
    vote = Vote.create(params[:vote])
    current_user.votes << vote
    increment_score(voteable_object, vote.value)
    render :json => { vote_id: vote.id, updated_score: voteable_object.score }
  end

  def update
    voteable_object = get_voteable_object(params[:vote])
    vote = Vote.find(params[:id])
    vote.update_attributes(params[:vote])
    increment_score(voteable_object, vote.value)

    render :json => { vote_id: vote.id, updated_score: voteable_object.score }
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
  def post_author(user_id)
    User.find(user_id).email
  end

  def post_advise(post_id)
  	@output = []
  	advice = Advice.where("adviseable_id =?", params[:id]).where("adviseable_type =?", "Post")
  	advice.each do |a|
  		user = User.find(a.user_id)
  		@output << {user_email: user.email, content: a.content}
  	end
  	@output
  end

  def comment_advise(comments)
    @output = []
    comments.each do |c|
      @output << Advice.where("adviseable_id =?", c.id).where("adviseable_type =?", "Comment")
    end
    @output
  end
end

app/views/advices/new.html.erb
<% if @comment %>
	<%= form_for [@post, @comment, @advice] do |f| %>
	  <%= f.hidden_field :type, :value => @comment.class %>
	  <%= f.hidden_field :id, :value => @comment.id %>
	  <%= f.text_area :content, :placeholder => 'give some advice on this comment' %><br>
	  <%= f.submit "Post" %>
	<% end %>
<% else %>
	<%= form_for [@post, @advice] do |f| %>
	  <%= f.label :content %>:<br>
	  <%= f.text_area :content %><br>
	  <%= f.hidden_field :type, :value => @post.class %>
	  <%= f.hidden_field :id, :value => @post.id %>
	  <%= f.submit "Post" %>
	<% end %>
<% end %>

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>

  <%= f.label :text %>:<br>
  <%= f.text_area :text %><br>
  <%= f.submit "Post" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
</head>

<body>
  <%= render "shared/topnav" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
</body>

</html>

app/views/posts/_comments.html.erb
<div class="comment">
	<div class="comment_box">
		<%= render partial: 'votes/vote', :locals => { :voteable => comments } %>
		  <%= link_to "Give Advice", new_post_comment_advice_path(@post, comments), class: "add_advice" %>
		  <% if comments.user_id == current_user.id %>
		  <%= link_to "Delete", post_comment_path(@post, comments), confirm: 'You sure?', method: :delete, class: "add_advice"%>
		  <% end %>
			<span class="comment_span"><%= comments.text %></span>
		<p>By: <%= comments.user.email %></p>
	<% if @comment_advice.flatten.first %>
		<% @comment_advice[comments_counter].each do |a| %>
		<% if a %>
			<div class="advice">Advice from <%= a.user.email %>: <%= a.content %></div>
			<% end %>
		<% end %>
	<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<h1>DBC Overflow: A Place for Public Feedback</h1>
<div class="post_index">
<% if user_signed_in? %>
  <h2><%= link_to "Give Feedback", new_post_path  %></h2>
<% end %>
<ul class="posts_list">
  <% @posts.each do |post| %>
    <li class="post_title"><%= post.title %> [<%= post.score %>] </li>
    <ul><li class="post_body"><%= post.text %> </li></ul>
    <% if user_signed_in? %>
      <ul class="post_body">
      <li class="post_author">A suggestion by <%= link_to post_author(post.user_id), user_path(post.user_id) %>.</li>
      <li class="post_link"> <%= link_to "View Discussion", post_path(post.id) %></li>
    </ul>
    <% end %>
  <% end %>
</ul>
</div>

app/views/posts/new.html.erb
<h1>Post your thoughts!</h1>
<p>We highly encourage you to make your comments</p>
<ul>
  <li>Specific!</li>
  <li>Actionable!</li>
  <li>and Kind!</li>
</ul>
<p>...even though this isn't Feedbackinator, it's still DBC.</p>

<%= render 'shared/post_form' %>

app/views/posts/show.html.erb
<div class="post_page">
  <div class="post_title">
    <%= render partial: 'votes/vote', :locals => { :voteable => @post } %>
    <%= @post.title %>
  </div>
  <div id='post'>
    <% if user_signed_in? %>
      <%= link_to "Give Advice", new_post_advice_path(@post), class: "add_advice" %>
      <%= link_to "Add Comment", new_post_comment_path(@post), class: "add_advice" %>
    <% end %>
    <% if @post.user_id == current_user.id %>
      <%= link_to "Delete", post_path(@post), confirm: 'You sure?', method: :delete, class: "add_advice" %>
    <% end %>
    <p><%= @post.text %></p>
    <p class="author">A suggestion from <%= link_to post_author(@post.user_id), user_path(@post.user_id) %></p>
    <% if @post_advice %>
      <%  @post_advice.each do |a| %>
        <div class="advice">
          <p>Advice from <%= a[:user_email] %>: <%= a[:content] %></p>
        </div>
      <% end %>
    <% end %>
    <div id="comment_box">
      <%= render partial: "comments", collection: @comments %>
    </div>
  </div>

</div>

app/views/shared/_comments.html.erb
<div class="comment">
  <p><%= comments.text %></p>
  <p>By: <%= comments.user.email %></p>
</div>

app/views/shared/_post_form.html.erb
<div class="form">
<%= form_for @post do |f| %>
  <%= f.text_field :title, placeholder: "Summary of your feedback", size: "70" %>
  <div><%= f.text_area :text, size: "60x10", placeholder: "Give us more detail here!" %></div>
  <%= f.submit "Give Feedback" %>
<% end %>
</div>

app/views/shared/_topnav.html.erb
<div id="topnav" class="nav">
  <%= link_to 'Home', root_path, :class => 'navbar-link brand' %>
  <%= link_to 'About', about_path, :class => 'navbar-link brand' %>
  <% if user_signed_in? %>
    <%= link_to 'Account', edit_user_registration_path, :class => 'navbar-link' %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <span id="user">Logged in as <strong><%= current_user.email %></strong>.</span>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1> Home Page </h1>

app/views/users/show.html.erb
<h1>This is <%= @user.email %>'s public profile!</h1>
<img src="http://www.gravatar.com/avatar/<%= @gravatar %>">

<h2>Here are <%= @user.email %>'s posts</h2>

<ul>
<% @posts.each do |post| %>
<li><%= link_to post.text, post_path(post.id) %></li>
<% end %>
</ul>

app/views/votes/_vote.html.erb
<span class="vote-buttons" data-vote-value='<%= current_user.vote_value(voteable) %>' data-vote-id="<%= current_user.vote_id(voteable) %>">

  <%= link_to image_tag('up_arrow.ico', height: "20", width: "20"), 
      votes_path(:vote => { :voteable_type => voteable.class.name, 
                            :voteable_id => voteable.id, value: 1 }), 
      :method => :post, 
      remote: true, 
      :class => "up" %>

  <%= link_to image_tag('down_arrow.ico', height: "20", width: "20"), 
      votes_path(:vote => { :voteable_type => voteable.class.name, 
                            :voteable_id => voteable.id, value: -1 }), 
      :method => :post, 
      remote: true, 
      :class => "down" %>

      [<span class="score"><%= voteable.score %></span>]

</span>